### ISSUE TITLE
Distorted image

### ISSUE THREAD

**Issue by arun54321** [rcanut/nhwcodec#3]
source image - https://i.ibb.co/JHRngPN/src.jpg
decoded image - https://i.ibb.co/3S2G73c/srcDEC.jpg

**Comment by rcanut** [comment]
Hello,

I can not reproduce the bug for now (the part of the image shifted to the left) , I'm on Windows.But I also did not try all the encoder settings, can you give me your command line that leads to this bug? -Also very unlikely, be sure that your bitmap source image has a 54-bytes header...-

Many thanks for testing NHW.
Cheers,
Raphael

**Comment by arun54321** [comment]
I didn't use any settings. 
```
nhw_encoder  1.bmp 
hw_decoder 1.nhw
```
I have used imagemagick to resize and crop the image to 512x512.

**Comment by arun54321** [comment]
The bmp file which is use. https://0x0.st/-qtu.zip

**Comment by rcanut** [comment]
Yes, it's that special type of bitmap file that is not handled by NHW.Supported bitmap input images must have a 54-bytes header, in short, size of the input 512x512 24bits bitmap image must be 786486 bytes.

If you are under windows, you can use Paint for example, to save (as bitmap 24bits) your initial unsupported bitmap image and so convert it to the supported one.

Hope it could help.
Cheers,
Raphael

**Comment by arun54321** [comment]
Okay.
